### ISSUE TITLE
可否支持测试任务？？

### ISSUE THREAD

**Issue by frg666** [wyp175/cidaren#1]
如题

**Comment by wyp175** [comment]
测试任务只要加个判断就可以
但是 现在没有准确的数据 
如有兴趣 可以提供一份fiddler在测试任务时每种题型的 jsonBody即可

**Comment by 1578339936** [comment]
[CustomRules.zip](https://github.com/wyp175/cidaren/files/4612865/CustomRules.zip)
稍作修改，貌似可用，请您检查一下

**Comment by frg666** [comment]
抓完了，看看这样行不
[词达人.zip](https://github.com/wyp175/cidaren/files/4619731/default.zip)
